[package]
resolver = "2"
name = "display"
version = "0.2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
bytemuck = { version = "1.7", features = ["derive"] }
nalgebra = { version = "*", features = ["bytemuck"] }

naga = { version = "*", features = ["glsl-in", "spv-out"], optional = true }
shaderc = { version = "0.7", optional = true }

env_logger = "0.8"
winit = "0.25"
wgpu = { version = "0.10", features = ["spirv"] }
log = "0.4"
png = "0.16"

tokio-stream = "0.1"
async-compression = { version = "0.3", features = ["tokio", "zlib"] }
# futures = { version = "0.3", features = ["async-await"] }

[dev-dependencies]
crc32fast = "1.2"
rand = "0.8"

[features]
default = ["shaderc"] # TODO: once shader validation in naga is better make naga the default

[profile.dev]
split-debuginfo = "unpacked"
